language: node_js
node_js: 
 - "10"

 cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: deploy
      if: (branch = master)
      install:
        - yarn
      script:
        - npm run build:doc
      after_script: 
        - cd site
        - git init
        - git add .
        - git commit -m "Update Document"
        - git push --force --quite master:gh-pages

env:
  global:
    - GH_REF: github.com/Bian2017/ii-fe.git