components:
  - title: 综述
    name: Docs
    items:
      - title: 介绍
        name: Introduction
  - title: 组件
    name: Docs
    groups:
      - title: 基础组件
        items:
          - title: 多选
            name: MultiSelect
